### ISSUE TITLE
Help with reading out DECT 440 (humidity)

### ISSUE THREAD

**Issue by helptiger** [linariii/fritz-homeautomation-csharp#1]
So far I have been using this great library to read the temperature of a DECT 200.
Now I have another Fritz DECT 440 and would like to read out the humidity too.
Does anyone have an example code or can help me a little?
I would be very pleased! Thanks

I'm using this for temperature (same as DECT 200):
`var myTemp = await FritzClient.GetTemperature(SessionID, AIN).ConfigureAwait(false);`

**Comment by linariii** [comment]
Thanks for using my library.

You can use `var devices = await FritzClient.GetDevices(Sid);` to get all devices (which already contain information about humidity if supported), afterwards you have to filter the devices. You can find an example (my Streamdeck Plugin for this Library) [here](https://github.com/linariii/streamdeck-fritz-smarthome/blob/main/FritzSmartHome/Actions/Humidity.cs)

I pushed a new version, since I found two small bugs in the device class which caused issues during de-serialization.

Please let me know if you need further assistance :)

**Comment by helptiger** [comment]
Thanks for the help. 😀 The solution can be so simple:

```
var deviceInfos = await FritzClient.GetDeviceInfos(<SessionID>, <AIN>);

if (deviceInfos?.Humidity.RelativeHumidity != null)
    ...
```
